Tag.create!(name: 'Personal')
Tag.create!(name: 'Work')
Tag.create!(name: 'Friends')
Tag.create!(name: 'Family')
Tag.create!(name: 'Motivation')
Tag.create!(name: 'Love')
Tag.create!(name: 'Life')
Tag.create!(name: 'Holiday')
Tag.create!(name: 'Willpower')
Tag.create!(name: 'Religion')
Tag.create!(name: 'Dream')

Victory.create!(title: "I made it to college", user_id: 1)
Victory.create!(title: "I lost 10 pounds", user_id: 1)
Victory.create!(title: "I got a promotion", user_id: 1)
Victory.create!(title: "I did not stay up all night watching game of thrones", user_id: 1)
Victory.create!(title: "I fed the cat", user_id: 1)
Victory.create!(title: "I made a chocolate cake", user_id: 1)