User.create!(first_name: "Huy", last_name: "Huynh", username: "huy", email: "huy@aol.com", city: "san jose", state: "ca", password: "huy")
User.create!(first_name: "John", last_name: "Dillion", username: "john", email: "john@aol.com", city: "austin", state: "tx", password: "john")
User.create!(first_name: "Liz", last_name: "Carter", username: "liz", email: "liz@aol.com", city: "new york", state: "ny", password: "liz")
User.create!(first_name: "Tina", last_name: "Lee", username: "tina", email: "tina@aol.com", city: "chicago", state: "il", password: "tina")

Tag.create!(name: 'Personal')
Tag.create!(name: 'Work')
Tag.create!(name: 'Friends')
Tag.create!(name: 'Family')
Tag.create!(name: 'Motivation')
Tag.create!(name: 'Love')
Tag.create!(name: 'Life')
Tag.create!(name: 'Holiday')
Tag.create!(name: 'Willpower')
Tag.create!(name: 'Religion')
Tag.create!(name: 'Dream')

Victory.create!(title: "I made it to college", user_id: 1)
Victory.create!(title: "I lost 10 pounds", user_id: 1)
Victory.create!(title: "I got a promotion", user_id: 1)
Victory.create!(title: "I did not stay up all night watching game of thrones", user_id: 1)
Victory.create!(title: "I fed the cat", user_id: 1)
Victory.create!(title: "I only had one glass of wine tonight", user_id: 1)
Victory.create!(title: "I spoke up to my boss", user_id: 1)
Victory.create!(title: "I went skydiving", user_id: 1)
Victory.create!(title: "I made a chocolate cake", user_id: 2)
Victory.create!(title: "I took a nap", user_id: 2)
Victory.create!(title: "I did an oil change myself", user_id: 2)
Victory.create!(title: "I ate sushi", user_id: 2)
Victory.create!(title: "I ran 10 miles today", user_id: 2)
Victory.create!(title: "I played games with my little niece", user_id: 2)
Victory.create!(title: "I found 20 dollars", user_id: 3)
Victory.create!(title: "I fixed the computer", user_id: 3)
Victory.create!(title: "I found my ring", user_id: 2)
Victory.create!(title: "I did not eat that cookie", user_id: 3)
Victory.create!(title: "I filed my taxes on time", user_id: 3)
Victory.create!(title: "I sang karaoke in public", user_id: 3)
Victory.create!(title: "I wrapped all the presents early", user_id: 3)
Victory.create!(title: "I met my next door neighbor", user_id: 3)